rust: bindgen: Exclude list functions with unsupported ABIs
CONFIG_LIST_HARDENED causes certain list functions to use what bindgen
considers an unsupported ABI:

panicked at 'Invalid or unknown abi 14 for function
"__list_del_entry_valid_or_report" (Function { name:
"__list_del_entry_valid_or_report", mangled_name:
Some("__list_del_entry_valid_or_report"), link_name:
None, signature: TypeId(ItemId(38153)), kind: Function,
linkage: External })',
/usr/share/cargo/registry/bindgen-0.68.1/codegen/mod.rs:4195:17

Exclude these, since they are internal functions we don't use directly
anyway.

Signed-off-by: Asahi Lina <lina@asahilina.net>